import type { ConcreteLogFormat } from "@/lib/types";

export interface LogSample {
  id: string;
  label: string;
  vendor: string;
  format: ConcreteLogFormat;
  description: string;
  content: string;
}

export const LOG_SAMPLES: LogSample[] = [
  {
    id: "palo-alto-cef",
    label: "Palo Alto threat alert",
    vendor: "Palo Alto Networks",
    format: "cef",
    description: "Blocked perimeter connection represented in ArcSight CEF.",
    content: "CEF:0|Palo Alto Networks|PAN-OS|11.1|THREAT-8001|Suspicious outbound connection|8|src=10.24.8.19 dst=198.51.100.42 spt=51244 dpt=443 proto=TCP act=blocked deviceExternalId=PA-EDGE-01 rt=Sep 24 2026 10:14:12 UTC msg=Known command and control endpoint",
  },
  {
    id: "qradar-leef",
    label: "QRadar VPN failure",
    vendor: "Cisco",
    format: "leef",
    description: "VPN authentication failure encoded as LEEF 2.0.",
    content: "LEEF:2.0|Cisco|ASA|9.18|VPN-AUTH-FAIL|^|src=203.0.113.77^dst=10.20.0.5^srcPort=49821^dstPort=443^sev=7^cat=authentication^usrName=analyst.ops^devTime=2026-09-24T10:15:03.000Z^action=denied",
  },
  {
    id: "rfc5424-syslog",
    label: "RFC 5424 firewall event",
    vendor: "Edge gateway",
    format: "syslog",
    description: "Structured syslog from a perimeter firewall.",
    content: '<134>1 2026-09-24T10:16:41.221Z edge-fw-02 filterd 4412 TCPDROP [net@32473 src="192.0.2.45" dst="10.0.12.8" spt="60122" dpt="22" proto="TCP" action="drop"] Inbound SSH attempt blocked',
  },
  {
    id: "suricata-eve",
    label: "Suricata IDS detection",
    vendor: "OISF Suricata",
    format: "json",
    description: "EVE JSON detection generated by an IDS sensor.",
    content: '{"timestamp":"2026-09-24T10:18:20.009Z","event_type":"alert","src_ip":"172.16.5.44","src_port":51888,"dest_ip":"10.1.4.20","dest_port":445,"proto":"TCP","in_iface":"eth1","alert":{"action":"blocked","signature_id":2024218,"signature":"ET EXPLOIT Possible SMB exploit attempt","category":"Attempted Administrator Privilege Gain","severity":1},"host":"ids-north-01"}',
  },
  {
    id: "fortigate-kv",
    label: "FortiGate traffic log",
    vendor: "Fortinet",
    format: "kv",
    description: "Vendor key-value traffic record with quoted values.",
    content: 'date=2026-09-24 time=15:49:02 devname="FGT-BORDER-01" devid="FG100FTK21000001" type="traffic" subtype="forward" level="warning" srcip=10.12.4.81 srcport=59182 dstip=192.0.2.90 dstport=53 proto=17 action="deny" service="DNS" msg="Denied DNS request"',
  },
  {
    id: "firewall-csv",
    label: "Generic firewall batch",
    vendor: "Generic",
    format: "csv",
    description: "Two firewall events in a portable CSV export.",
    content: "timestamp,device,src_ip,src_port,dst_ip,dst_port,protocol,action,severity,message\n2026-09-24T10:20:01Z,branch-fw-01,10.8.0.14,51004,203.0.113.9,443,tcp,allow,3,TLS egress allowed\n2026-09-24T10:20:04Z,branch-fw-01,198.51.100.9,44210,10.8.0.2,3389,tcp,deny,8,RDP ingress blocked",
  },
  {
    id: "gateway-xml",
    label: "Gateway XML event",
    vendor: "Generic",
    format: "xml",
    description: "Single perimeter event from a legacy XML export.",
    content: "<event><timestamp>2026-09-24T10:21:08Z</timestamp><device>legacy-gw-04</device><source><ip>192.0.2.8</ip><port>58820</port></source><destination><ip>10.40.1.4</ip><port>25</port></destination><protocol>tcp</protocol><action>blocked</action><severity>high</severity><message>SMTP relay attempt denied</message></event>",
  },
];

export const DEFAULT_SAMPLE = LOG_SAMPLES[0];
